services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    container_name: api
    networks:
      - api/streamlit
    ports:
      - "2222:2222"
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile-streamlit
    container_name: streamlit
    environment:
      - API_URL=api
    networks:
      - api/streamlit
    ports:
      - "1111:1111"

networks:
  api/streamlit:
    driver: bridge
