networks:
  api/streamlit:
    driver: bridge
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    container_name: api
    networks:
      - api/streamlit
    ports:
      - "2222:2222"
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile-streamlit
    container_name: streamlit
    environment:
      - API_URL=api
    networks:
      - api/streamlit
    ports:
      - "1111:1111"

  # Not working yet
  # data_service:
  #   build :
  #     context: src/data_service/
  #     dockerfile: data_service_dockerfile
  #   image: data_service:latest
  #   container_name: data_service
  #   command: compose -f docker-compose.yml build 
  #   volumes:
  #       - ./src/:/src
  #       - type: bind
  #         source: src/
  #         target: /app_data/src
  #       - ./data/:/data
  #       - type: bind
  #         source: data/
  #         target: /app_data/data
  #       - /var/run/docker.sock:/var/run/docker.sock
  
 

