services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    container_name: api
    image: api:latest
    env_file:
      - ./api/.env
    environment:
      - DB_PATH=/app/database.db
      - PREDICTION_PATH=/app/previsions.csv
      - COORDINATE=/app/cities_coordinates.csv
    volumes:
      - ./database.db:/app/database.db
      - ./data/predictions/current_prediction.csv:/app/previsions.csv
      - ./data/raw_data/cities_coordinates.csv:/app/cities_coordinates.csv
    networks:
      - api_streamlit
      - api_prometheus
    ports:
      - "2222:2222"

  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile-streamlit
    container_name: streamlit
    image: streamlit:latest
    env_file:
      - ./streamlit/.env
    environment:
      - API_URL=api
    networks:
      - api_streamlit
    ports:
      - "1111:1111"
    depends_on:
      - api


  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile-prometheus
    container_name: prometheus
    image: prometheus:latest
    environment:
      - TARGET_HOST=api
    networks:
      - api_prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api

networks:
  api_streamlit:
    name: api_streamlit
    driver: bridge
  api_prometheus:
    name: api_prometheus
    driver: bridge
