stages:
  reset_data:
    cmd: python .\src\data_service\ingest_data\reset_data.py
    deps:
    - .\src\data_service\ingest_data\reset_data.py
    outs:
    - .\data\current_data\current_data.csv
  ingest_new_data:
    cmd: python .\src\data_service\ingest_data\ingest_new_data.py
    deps:
    - .\data\current_data\current_data.csv
    - .\src\data_service\ingest_data\ingest_new_data.py
    outs:
    - .\data\current_data\uptodate_data.csv
  complete_nas:
    cmd: python ./src/data_service/complete_nas/complete_nas.py
    deps:
    - .\data\current_data\uptodate_data.csv
    - ./src/data_service/complete_nas/complete_nas.py
    outs:
    -  ./data/processed_data/nas_completed_data.csv

