#syntax=docker/dockerfile:1

FROM python:3.9-slim

WORKDIR /app/

COPY requirements_prometheus.txt /app/

RUN pip install --no-cache-dir -r /app/requirements_prometheus.txt

COPY . /app/

EXPOSE 3333

CMD ["prometheus", "--config.file=prometheus.yml"]
