services:
  mflow:
      build:
        context: /mlfow
        dockerfile: ./tracking_dockerfile
      image: tracking:latest
      container_name: tracking
  dvc_fetch:
    build:
        context: /dvc
        dockerfile: ./dvc_fetch_dockerfile
    image: dvc_fetch:latest
    container_name: dvc_fetch
  