# env_file:
#   - path: ../docker.env
services:
  reset_data:
      build:
        context: ./ingest_data
        dockerfile: ./reset_data_dockerfile
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data/:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: reset_data:latest
      container_name: reset_data
      env_file:
        - path: ../docker.env
  ingest_data:
      build:
        context: ./ingest_data
        dockerfile: ./ingest_data_dockerfile
      depends_on:
        reset_data:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: ingest_data:latest
      container_name: ingest_data
      env_file:
        - path: ../docker.env
  complete_nas:
      build:
        context: ./complete_nas
        dockerfile: ./complete_nas_dockerfile
      depends_on:
        ingest_data:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: complete_nas:latest
      container_name: complete_nas
      env_file:
        - path: ../docker.env
  features:
      build:
        context: ./features
        dockerfile: ./features_dockerfile
      depends_on:
        complete_nas:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: features:latest
      container_name: features
      env_file:
        - path: ../docker.env
  encode_data:
      build:
        context: ./encode_data
        dockerfile: ./encode_data_dockerfile
      depends_on:
        features:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: encode_data:latest
      container_name: encode_data
      env_file:
        - path: ../docker.env

  split_data:
      build:
        context: ./split_data
        dockerfile: ./split_data_dockerfile
      depends_on:
        encode_data:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: split_data:latest
      container_name: split_data
      env_file:
        - path: ../docker.env

  scale_data:
      build:
        context: ./scale_data
        dockerfile: ./scale_data_dockerfile
      depends_on:
        split_data:
          condition: service_completed_successfully
      volumes:
        - ../../src:/src
        - type: bind
          source: ../../src
          target: /app/src
        - ../../data:/data
        - type: bind
          source: ../../data
          target: /app/data
      image: scale_data:latest
      container_name: scale_data
      env_file:
        - path: ../docker.env
